// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ulimvxqcynzvuokwsxld.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVsaW12eHFjeW56dnVva3dzeGxkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNjY2NjQsImV4cCI6MjA3NDY0MjY2NH0.rGXoOy9QaHKuL62jD-wk0xZD9WV82jA9g25rrtM3Qss";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});